### ISSUE TITLE
Rename to robotology-vcpkg-ports?

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-vcpkg-binary-ports#12]
Now that we start adding also non-binary ports (see https://github.com/robotology/robotology-vcpkg-binary-ports/pull/11) it could make sense to rename the repo. In the past both @pattacini and @drdanz mentioned that they agreed with this, but I wanted to double check.

cc @GiulioRomualdi

**Comment by pattacini** [comment]
Fine with me 👍🏻

**Comment by drdanz** [comment]
Fine with me too... :+1:

**Comment by traversaro** [comment]
Done.
