### ISSUE TITLE
Regression on vcpkg master as of 2021/01/23

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-vcpkg-binary-ports#18]
The last nightly job (https://github.com/robotology/robotology-vcpkg-ports/actions/runs/505136779) failed when installing a vcpkg port after installing a custom port, with error:
~~~
Computing installation plan...
Error: while loading casadi:
The port directory (C:\vcpkg-test\vcpkg\ports\casadi) does not exist
Error: failed to load port from C:\vcpkg-test\vcpkg\ports\casadi
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
~~~

**Comment by traversaro** [comment]
At a first glance the last commit that is safe seems to be https://github.com/microsoft/vcpkg/commit/5065bf984abad0d3ad79f73cdc59ee95733c91ad .

**Comment by traversaro** [comment]
By doing a quick bisect (see https://github.com/robotology/robotology-vcpkg-ports/pull/19) this seems to be a regression introduced by https://github.com/microsoft/vcpkg/pull/15709 .

**Comment by lfarelka** [comment]
Please help me. When trying to install uwebsockets, an error message appears:
Error: When loading uwebsokets:
Port Directory (C:\vcpkg-master\ports\uwebsokets ) does not exist
Mistake: failed to load port from C:\vcpkg-master\ports\uwebsokets
note: updating vcpkg by restarting bootstrap-vcpkg may fix this error.
Even after reloading using bootstrap-vcpkg and other manipulations, it is not possible to load. I must say right away I have no idea about the problem, especially how to solve it. I need uwebsokets to learn how to write a kernel in C++ by video. There it was indicated that you need to install the vcpkg library, but it does not work

**Comment by traversaro** [comment]
@lfarelka This is not the place for unrelated requests, can you post your questio somewhere else? In any case, in your case it seems that there was a typo uwebsokets/uwebso**c**kets .

**Comment by traversaro** [comment]
As validated in https://github.com/robotology/robotology-vcpkg-ports/pull/19, the issue https://github.com/microsoft/vcpkg/issues/15836 was fixed, so we can close also this issue as well!
